# Nota: Este tipo no tiene propiedad "id" porque va a usarse de forma embebida dentro de otro tipo.
type: object
properties:
  id:
    type: string
    format: uuid
    description: The unique identifier of the image
  url:
    type: string
    format: url
    description: The url of the image
    minLength: 5
    maxLength: 500
    example: https://test.org/wp-content/uploads/2019/08/iphone.jpg
  altText:
    type: string
    nullable: true
    minLength: 3
    maxLength: 255
required:
  - id
  - url