get:
  tags:
    - Product
  summary: Get a list of products
  description: Get a list of products.
  operationId: listProducts
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/v1/product_list.yaml
post:
  tags: 
    - Product
  summary: Create a new product
  description: Create a new product.
  operationId: createProduct
  requestBody: 
    content:
      application/json:
        schema: 
          $ref: ../../components/schemas/v1/product_create.yaml
  responses: 
    '201':
      description: Created
      headers:
        Location:
          description: Location of the new resource
          schema: 
            type: string
            example: /v1/products/c6fa6248-32a2-4afe-9a2d-c88905c9eb76
    '400':
      description: Bad Request
      content:
        application/json:
          schema: 
            $ref: ../../components/schemas/Problem.yaml
  